// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddPropertyToBinding
{
    internal sealed partial class Vsix
    {
        public const string Id = "AddPropertyToBinding.597de914-39e0-465b-b704-7d9a5f166b55";
        public const string Name = "Add Property To Binding";
        public const string Description = @"It's adding property and field to binding in regions in viewmodelIt";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
